name: Cracking the coding interview CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
    - name: Install dependencies and Run unit tests
      run: |
        bun install --frozen-lockfile
        bun run test
      env:
        CI: true
